A workflow for publishing python package release
trueagi-io/hyperon-experimental pull request #277
Opened 2023-04-24 23:21 UTC by wenwei-dev

2023-04-25 15:31 UTC, vsbogd requested changes
I have tried to install the package from the [test repository](https://test.pypi.org/project/hyperon/0.1.3.4/) and looks like it doesn't contain `.so` libraries.

2023-04-25 15:31 UTC, vsbogd commented on .github/workflows/python-publish.yml
> +        chrpath -d ./python/*.so  ./c/cargo/*.so
I would include this step into `CMakeLists.txt` files which build the corresponding libraries.

2023-04-25 15:38 UTC, vsbogd commented
Also it is interesting question how could I test it locally. Could you please describe the steps you did for testing?

2023-04-29 15:26 UTC, wenwei-dev commented on python/setup.py
> +          "local_scheme": "node-and-timestamp"
This uses the scm (git tag) to determine the version.

2023-04-29 15:27 UTC, wenwei-dev commented on python/setup.py
> +          "local_scheme": "node-and-timestamp"
For example, if it is built on git tag v1.0.0, then the version will be v1.0.0

2023-05-03 20:49 UTC, vsbogd commented
@wenwei-dev, the problem with incorrect Python version is caused by the fact the GitHub Actions environment has two versions installed:
- `python3-dev` Ubuntu package
- `python` from `actions/python-setup`
By default CMake prefers the system version I am not sure why. But anyway we need to force it find the version we need.
It can be done by specifying `Python3_EXECUTABLE` parameter for the `cmake` command:
```sh
cmake -DPython3_EXECUTABLE=`which python` -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release ..
```
here: https://github.com/wenwei-dev/hyperon-experimental/blob/d7cdc10489c15e1b9bb0d1af84682899723934ca/.github/workflows/python-publish.yml#L85

Also I see that `python-publish.yml` use two different versions in different lines. The `python3` here: https://github.com/wenwei-dev/hyperon-experimental/blob/d7cdc10489c15e1b9bb0d1af84682899723934ca/.github/workflows/python-publish.yml#L77 should be replaced by `python`. This issue probably was copied from `ci.yml`, it also uses `python3` which is incorrect. I will fix it.

2023-05-03 21:03 UTC, vsbogd commented
Well, both issues are copied from `ci.yml`. I have fixed them by https://github.com/trueagi-io/hyperon-experimental/pull/285

2023-06-21 21:19 UTC, vsbogd commented on .github/workflows/python-publish.yml
> +    needs: build-ubuntu-2004
implemented in https://github.com/wenwei-dev/hyperon-experimental/pull/2

2023-06-21 21:20 UTC, vsbogd approved these changes
Looks good to me.

2023-06-21 21:37 UTC, merged