Update requirements.txt
trueagi-io/hyperon-experimental pull request #627
Opened 2024-03-18 14:42 UTC by CICS-Oleg

2024-03-18 15:23 UTC, Necr0x0Der commented
I'm not sure in general that these requirements should be in `python` folder of hyperon in general since they are needed only for das-gate

2024-03-19 05:46 UTC, vsbogd requested changes
Current list of requirements is kept in `pyproject.toml` file (see `project.dependencies` setting). If we keep das-gate as a part of the `hyperon` Python package then we should keep requirements there. Otherwise we need to distribute it as a separate Python package.

2024-03-19 09:03 UTC, Necr0x0Der commented
DAS is invoked as MeTTa extension/module. While it is placed in hyperon package for convenience, putting its requirements into hyperon requirements is not good I think

2024-03-19 12:08 UTC, vsbogd commented
> DAS is invoked as MeTTa extension/module. While it is placed in hyperon package for convenience, putting its requirements into hyperon requirements is not good I think

Let's put requirements into a separate file in `python/hyperon/exts/das_gate` directory as discussed.

2024-03-22 11:37 UTC, vsbogd commented on python/requirements.txt
Please remove this file it doesn't make sense. All dependencies are kept in `pyproject.toml` file.

2024-03-27 11:02 UTC, vsbogd approved these changes

2024-03-27 11:26 UTC, merged